In [113]:
import pandas as pd

df = pd.read_csv("C:\\HEMNATH\\data\\bpo_agent_dataset_final.csv")

In [119]:
df[df["attendance_status"] != "Holiday"].head()

,date,agent_id,agent_name,team,gender,age,attendance_status,shift_start_time,shift_end_time,login_time,...,training_time,talk_time,hold_time,after_call_work,avg_handle_time,calls_handled,total_login,effective_work_hours,occupancy_percent,quality_score
100,2025-01-02,Moni001,Monika Gupta,Retention,Female,27,Present,09:00:00,18:00:00,2025-01-02 09:04:00,...,0 days 00:00:00,0 days 00:03:33,0 days 00:00:29,0 days 00:00:50,0 days 00:04:52,57,0 days 08:56:00,8.016667,57.671518,75.35
101,2025-01-02,Sanj002,Sanjay Rao,Inbound,Female,21,Week Off,09:00:00,18:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.00
102,2025-01-02,Sneh003,Sneha Nair,Retention,Female,21,Week Off,09:00:00,18:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.00
103,2025-01-02,Mano004,Manoj Rao,Retention,Male,33,Uninformed Leave,09:00:00,18:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.00
104,2025-01-02,Vign005,Vignesh Das,Inbound,Male,29,Week Off,09:00:00,18:00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,0.00

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18100 entries, 0 to 18099
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  18100 non-null  object
 1   agent_id              18100 non-null  object
 2   agent_name            18100 non-null  object
 3   team                  18100 non-null  object
 4   gender                18100 non-null  object
 5   age                   18100 non-null  int64
 6   attendance_status     18100 non-null  object
 7   shift_start_time      18100 non-null  object
 8   shift_end_time        18100 non-null  object
 9   login_time            10862 non-null  object
 10  logout_time           10862 non-null  object
 11  tea_break_time        10862 non-null  object
 12  lunch_break_time      10862 non-null  object
 13  bio_break_time        10862 non-null  object
 14  training_time         10862 non-null  object
 15  talk_time             10862 non-null  object
 16  hold_time             10862 non-null  object
 17  after_call_work       10862 non-null  object
 18  avg_handle_time       10862 non-null  object
 19  calls_handled         18100 non-null  int64
 20  total_login           10862 non-null  object
 21  effective_work_hours  10862 non-null  float64
 22  occupancy_percent     10862 non-null  float64
 23  quality_score         18100 non-null  float64
dtypes: float64(3), int64(2), object(19)
memory usage: 3.3+ MB

In [116]:
df.describe(include='all')

,date,agent_id,agent_name,team,gender,age,attendance_status,shift_start_time,shift_end_time,login_time,...,training_time,talk_time,hold_time,after_call_work,avg_handle_time,calls_handled,total_login,effective_work_hours,occupancy_percent,quality_score
count,18100,18100,18100,18100,18100,18100.000000,18100,18100,18100,10862,...,10862,10862,10862,10862,10862,18100.000000,10862,10862.000000,10862.000000,18100.000000
unique,181,100,100,3,2,NaN,7,4,4,3331,...,61,80,30,40,144,NaN,21,NaN,NaN,NaN
top,2025-01-01,Moni001,Monika Gupta,Outbound,Male,NaN,Present,11:00:00,20:00:00,2025-02-01 09:15:00,...,0 days 00:00:00,0 days 00:03:25,0 days 00:00:14,0 days 00:00:57,0 days 00:04:49,NaN,0 days 04:00:00,NaN,NaN,NaN
freq,100,181,181,6516,10136,NaN,10231,4900,4900,11,...,9822,167,386,321,159,NaN,631,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,28.950000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,32.836630,NaN,7.587484,56.972098,51.926300
std,NaN,NaN,NaN,NaN,NaN,5.974067,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,29.022796,NaN,1.026140,14.877503,42.703387
min,NaN,NaN,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,2.266667,5.222222,0.000000
25%,NaN,NaN,NaN,NaN,NaN,23.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,7.800000,46.198188,0.000000
50%,NaN,NaN,NaN,NaN,NaN,28.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,41.000000,NaN,7.900000,55.850454,78.830000
75%,NaN,NaN,NaN,NaN,NaN,36.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,58.000000,NaN,8.000000,66.867075,88.450000
max,NaN,NaN,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,99.000000,NaN,8.083333,163.243243,98.000000

In [120]:
#First check all the columns are in proper formathe and nameing 
df.columns = df.columns.str.lower()
df = df.rename(columns= {'avg_handle_time_time' : "avg_handle_time"})

In [97]:
df.columns

Index(['date', 'agent_id', 'agent_name', 'team', 'gender', 'age',
       'attendance_status', 'shift_start_time', 'shift_end_time', 'login_time',
       'logout_time', 'tea_break_time', 'lunch_break_time', 'bio_break_time',
       'training_time', 'talk_time', 'hold_time', 'after_call_work',
       'avg_handle_time', 'calls_handled', 'total_login',
       'effective_work_hours', 'occupancy_percent', 'quality_score'],
      dtype='object')

In [122]:
time_cols = [
    "tea_break_time",
    "lunch_break_time",
    "bio_break_time",
    "training_time",
    "talk_time",
    "hold_time",
    "after_call_work",
    "avg_handle_time",
    "total_login"
]

for col in time_cols:
    df[col] = df[col].astype(str).str.split().str[-1]

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18100 entries, 0 to 18099
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  18100 non-null  object
 1   agent_id              18100 non-null  object
 2   agent_name            18100 non-null  object
 3   team                  18100 non-null  object
 4   gender                18100 non-null  object
 5   age                   18100 non-null  int64
 6   attendance_status     18100 non-null  object
 7   shift_start_time      18100 non-null  object
 8   shift_end_time        18100 non-null  object
 9   login_time            10862 non-null  object
 10  logout_time           10862 non-null  object
 11  tea_break_time        18100 non-null  object
 12  lunch_break_time      18100 non-null  object
 13  bio_break_time        18100 non-null  object
 14  training_time         18100 non-null  object
 15  talk_time             18100 non-null  object
 16  hold_time             18100 non-null  object
 17  after_call_work       18100 non-null  object
 18  avg_handle_time       18100 non-null  object
 19  calls_handled         18100 non-null  int64
 20  total_login           18100 non-null  object
 21  effective_work_hours  10862 non-null  float64
 22  occupancy_percent     10862 non-null  float64
 23  quality_score         18100 non-null  float64
dtypes: float64(3), int64(2), object(19)
memory usage: 3.3+ MB

In [127]:
df[df["attendance_status"] != "Holiday"].head()

,date,agent_id,agent_name,team,gender,age,attendance_status,shift_start_time,shift_end_time,login_time,...,training_time,talk_time,hold_time,after_call_work,avg_handle_time,calls_handled,total_login,effective_work_hours,occupancy_percent,quality_score
100,2025-01-02,Moni001,Monika Gupta,Retention,Female,27,Present,09:00:00,18:00:00,2025-01-02 09:04:00,...,00:00:00,00:03:33,00:00:29,00:00:50,00:04:52,57,08:56:00,8.016667,57.671518,75.35
101,2025-01-02,Sanj002,Sanjay Rao,Inbound,Female,21,Week Off,09:00:00,18:00:00,None,...,nan,nan,nan,nan,nan,0,nan,NaN,NaN,0.00
102,2025-01-02,Sneh003,Sneha Nair,Retention,Female,21,Week Off,09:00:00,18:00:00,None,...,nan,nan,nan,nan,nan,0,nan,NaN,NaN,0.00
103,2025-01-02,Mano004,Manoj Rao,Retention,Male,33,Uninformed Leave,09:00:00,18:00:00,None,...,nan,nan,nan,nan,nan,0,nan,NaN,NaN,0.00
104,2025-01-02,Vign005,Vignesh Das,Inbound,Male,29,Week Off,09:00:00,18:00:00,None,...,nan,nan,nan,nan,nan,0,nan,NaN,NaN,0.00

In [130]:
df.replace("nan", None, inplace=True)

In [132]:
from sqlalchemy import create_engine

username = "root"
password = "1234"
host = "localhost"
port = "3306"
database = "WFM_PROJECT"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

table_name = "agent_performance"
df.to_sql(table_name, engine, if_exists="replace", index=False)


pd.read_sql("SELECT * FROM agent_performance LIMIT 5;", engine)

,date,agent_id,agent_name,team,gender,age,attendance_status,shift_start_time,shift_end_time,login_time,...,training_time,talk_time,hold_time,after_call_work,avg_handle_time,calls_handled,total_login,effective_work_hours,occupancy_percent,quality_score
0,2025-01-01,Moni001,Monika Gupta,Retention,Female,27,Holiday,09:00:00,18:00:00,None,...,None,None,None,None,None,0,None,None,None,0.0
1,2025-01-01,Sanj002,Sanjay Rao,Inbound,Female,21,Holiday,09:00:00,18:00:00,None,...,None,None,None,None,None,0,None,None,None,0.0
2,2025-01-01,Sneh003,Sneha Nair,Retention,Female,21,Holiday,09:00:00,18:00:00,None,...,None,None,None,None,None,0,None,None,None,0.0
3,2025-01-01,Mano004,Manoj Rao,Retention,Male,33,Holiday,09:00:00,18:00:00,None,...,None,None,None,None,None,0,None,None,None,0.0
4,2025-01-01,Vign005,Vignesh Das,Inbound,Male,29,Holiday,09:00:00,18:00:00,None,...,None,None,None,None,None,0,None,None,None,0.0